name: halotec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^1.2.2
  image_picker: ^0.8.5+3
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.9
  intl: ^0.18.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login.png
    - assets/flipped.png
    - assets/register.png
    - assets/placeholder.png
    - assets/semicircle.png
    - assets/download.jpg